services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: algojudge
      POSTGRES_USER: algojudge_user
      POSTGRES_PASSWORD: algopassword
      POSTGRES_INITDB_ARGS: "--auth-host=md5 --auth-local=md5"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U algojudge_user -d algojudge"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - algojudge_network

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      DATABASE_URL: postgresql://algojudge_user:algopassword@db:5432/algojudge
      OLLAMA_HOST: http://host.docker.internal:11434
    depends_on:
      db:
        condition: service_healthy
    privileged: true
    networks:
      - algojudge_network

volumes:
  postgres_data:

networks:
  algojudge_network:
    driver: bridge
