services:
  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: algojudge
      POSTGRES_USER: algojudge_user
      POSTGRES_PASSWORD: algopassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - algojudge_network

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      DATABASE_URL: postgresql://algojudge_user:algopassword@db:5432/algojudge
      OLLAMA_HOST: http://host.docker.internal:11434
    depends_on:
      - db
    privileged: true
    networks:
      - algojudge_network

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    depends_on:
      - backend
    networks:
      - algojudge_network

volumes:
  postgres_data:

networks:
  algojudge_network:
    driver: bridge
